# Generated by Django 4.1.6 on 2023-02-03 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('cut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schemas.typeofschemas')),
            ],
        ),
    ]
