# Generated by Django 4.1.6 on 2023-02-05 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schema',
            name='column_separator',
        ),
        migrations.RemoveField(
            model_name='schema',
            name='string_character',
        ),
        migrations.CreateModel(
            name='StringCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_character', models.CharField(max_length=1)),
                ('cut_string_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schemas.schema')),
            ],
        ),
        migrations.CreateModel(
            name='ColumnSeparator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_separator', models.CharField(max_length=1)),
                ('cut_column_separator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schemas.schema')),
            ],
        ),
    ]
