# Generated by Django 4.1.6 on 2023-02-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0006_typeofschemastext_typeofschemasphonenumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnSeparatorView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_separator_view', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='StringCharacterView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_character_view', models.CharField(max_length=1)),
            ],
        ),
    ]
