# Generated by Django 4.1.6 on 2023-02-05 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0007_columnseparatorview_stringcharacterview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnseparator',
            name='column_separator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schemas.columnseparatorview'),
        ),
        migrations.AlterField(
            model_name='stringcharacter',
            name='string_character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schemas.stringcharacterview'),
        ),
    ]
