# Generated by Django 4.1.6 on 2023-02-05 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0008_alter_columnseparator_column_separator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stringcharacter',
            name='cut_string_character',
        ),
        migrations.RemoveField(
            model_name='stringcharacter',
            name='string_character',
        ),
        migrations.DeleteModel(
            name='ColumnSeparator',
        ),
        migrations.DeleteModel(
            name='ColumnSeparatorView',
        ),
        migrations.DeleteModel(
            name='StringCharacter',
        ),
        migrations.DeleteModel(
            name='StringCharacterView',
        ),
    ]
