# Generated by Django 4.1.6 on 2023-02-05 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0009_remove_stringcharacter_cut_string_character_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnSeparatorView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_separator_view', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='StringCharacterView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_character_view', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='StringCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cut_string_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schemas.schema')),
                ('string_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schemas.stringcharacterview')),
            ],
        ),
        migrations.CreateModel(
            name='ColumnSeparator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_separator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schemas.columnseparatorview')),
                ('cut_column_separator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schemas.schema')),
            ],
        ),
    ]
