# Generated by Django 4.1.6 on 2023-02-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0010_columnseparatorview_stringcharacterview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnseparator',
            name='column_separator',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='stringcharacter',
            name='string_character',
            field=models.CharField(max_length=1),
        ),
    ]
