# Generated by Django 4.1.6 on 2023-02-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0012_rename_cut_address_typeofschemasdate_cut_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='column_separator',
            field=models.CharField(default=';', max_length=1),
        ),
        migrations.AddField(
            model_name='schema',
            name='string_character',
            field=models.CharField(default="'", max_length=1),
        ),
    ]
