# Generated by Django 4.1.6 on 2023-02-07 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0014_typecategories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typecategories',
            name='cut_type',
        ),
        migrations.CreateModel(
            name='ColumnsSchemas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cut_schemas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schemas.schema')),
                ('cut_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schemas.typecategories')),
            ],
        ),
    ]
